### ISSUE TITLE
Slack channel broken link

### ISSUE THREAD

**Issue by albertopastormr** [teddywilson/tell-me-when-ableton-supports-m1#2]
The Slack channel link that is in the README doesn't work, it's no longer active.
![link down](https://i.gyazo.com/d6f85439fd53eb850b88685144d0612c.png)

**Comment by teddywilson** [comment]
Ah, shoot. I didn't realize they expire in 30 days! Updating now. I wonder if there's an easier way...

**Comment by teddywilson** [comment]
Updated!
